# This project config file describes your project. See looper docs for details.
name: test_project # The name that summary files will be prefaced with

pep_version: 2.0.0
sample_table: test_annotation.csv  # sheet listing all samples in the project

looper:  # relative paths are relative to this config file
  output_dir: pepatac_test 
  pipeline_interfaces: ../../project_pipeline_interface.yaml  # PATH to the directory where looper will find the pipeline repository. 

sample_modifiers:
  append:
    pipeline_interfaces: ../../sample_pipeline_interface.yaml
  derive:
    attributes: [read1, read2]
    sources:
      test_data_R1: "examples/data/{sample_name}_chr22_r1.fastq.gz"
      test_data_R2: "examples/data/{sample_name}_chr22_r2.fastq.gz"
  imply:
    - if: 
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then: 
        genome: hg38_chr22
        macs_genome_size: hs
        prealignments: ["rCRSd"]
        aligner: bowtie2         # Default. [options: bwa]
        deduplicator: samblaster # Default. [options: picard]
        trimmer: skewer          # Default. [options: pyadapt, trimmomatic]
        peak_type: fixed         # Default. [options: variable]
        extend: "250"            # Default. For fixed-width peaks, extend this distance up- and down-stream.
        frip_ref_peaks: None     # Default. Use an external reference set of peaks instead of the peaks called from this run
        #TSS_name: "/project/shefflab/genomes_v04_210301/alias/hg38/refgene_anno/default/hg38_TSS.bed"
        blacklist: /project/shefflab/genomes_v04_210301/alias/hg38/blacklist/default/hg38_blacklist.bed.gz
        anno_name: /project/shefflab/genomes_v04_210301/alias/hg38/feat_annotation/default/hg38_annotations.bed.gz
